import React, { useMemo, useState } from "react";
import "./UIScreenshotIssues.css"
const SeveritySection = ({ title, items }) => {
  if (!items?.length) return null;
  return (
    <div className="ui-issues-section">
      <div className="ui-issues-section-title">{title} ({items.length})</div>
      <ul className="ui-issues-list">
        {items.map((it, idx) => (
          <li key={idx} className="ui-issues-item">
            <div className="ui-issue-name">{it.issue}</div>
            {it.description ? <div className="ui-issue-desc">{it.description}</div> : null}
            {it.location_hint ? <div className="ui-issue-loc">Location: {it.location_hint}</div> : null}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default function UIScreenshotIssues({
  status,            // 'idle' | 'loading' | 'ready' | 'error'
  error,
  results,           // [{ screenshot_url, screenshot_name?, ui_score, critical, moderate, minor, raw? }]
  onAnalyzeClick,    // () => void
}) {
  const [activeIdx, setActiveIdx] = useState(0);

  const active = useMemo(() => results?.[activeIdx], [results, activeIdx]);

  // Backend base (optionally set VITE_API_BASE_URL=http://localhost:8000)
  const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

  const resolveUrl = (u) => {
    if (!u) return "";
    if (/^https?:\/\//i.test(u)) return u;     // already absolute
    if (u.startsWith("/")) return `${API_BASE}${u}`;
    return `${API_BASE}/${u}`;
  };

  return (
    <div className="dashboard-card ui-issues-card">
      <div className="ui-issues-header">
        <div>
          <h3 className="card-title" style={{ marginBottom: 4 }}>UI Screenshot Issues</h3>
          <div className="ui-issues-subtitle">
            {status === "idle" && "Run tests, then analyze screenshots."}
            {status === "loading" && "Analyzing screenshots..."}
            {status === "ready" && `${results?.length || 0} screenshots analyzed`}
            {status === "error" && "Failed to analyze screenshots"}
          </div>
        </div>

        <button
          className="run-button"
          style={{ padding: "8px 12px", backgroundColor: "#334155", border: "1px solid #475569" }}
          onClick={onAnalyzeClick}
          disabled={status === "loading"}
          title="Analyze all screenshots generated by the latest automation run"
        >
          {status === "loading" ? "Analyzing..." : "Analyze Screenshots"}
        </button>
      </div>

      {status === "error" ? (
        <div className="ui-issues-error">
          {error || "Unknown error"}
        </div>
      ) : null}

      {status !== "ready" || !results?.length ? null : (
        <div className="ui-issues-body">
          {/* Left: thumbnail list */}
          <div className="ui-issues-listpane">
            {results.map((r, idx) => (
              <button
                key={`${r.screenshot_url}-${idx}`}
                className={`ui-issues-thumb ${idx === activeIdx ? "active" : ""}`}
                onClick={() => setActiveIdx(idx)}
                type="button"
              >
                <div className="ui-issues-thumb-title">
                  {r.screenshot_name || `Screenshot ${idx + 1}`}
                </div>
                <div className="ui-issues-thumb-meta">
                  Score: <b>{Number.isFinite(r.ui_score) ? r.ui_score : "—"}</b>
                  <span className="ui-issues-badges">
                    {!!r.critical?.length && <span className="badge badge-critical">C:{r.critical.length}</span>}
                    {!!r.moderate?.length && <span className="badge badge-moderate">M:{r.moderate.length}</span>}
                    {!!r.minor?.length && <span className="badge badge-minor">m:{r.minor.length}</span>}
                  </span>
                </div>
              </button>
            ))}
          </div>

          {/* Right: preview + issues */}
          <div className="ui-issues-detail">
            <div className="ui-issues-previewRow">
              <div className="ui-issues-preview">
                <img
                  src={resolveUrl(active?.screenshot_url)}
                  alt={active?.screenshot_name || "screenshot"}
                  className="ui-issues-image"
                  loading="lazy"
                />
              </div>

              <div className="ui-issues-summary">
                <div className="ui-issues-score">
                  UI Score: <span className="ui-issues-scoreValue">{Number.isFinite(active?.ui_score) ? active.ui_score : "—"}</span>
                </div>
                <div className="ui-issues-counts">
                  <div>Critical: <b>{active?.critical?.length || 0}</b></div>
                  <div>Moderate: <b>{active?.moderate?.length || 0}</b></div>
                  <div>Minor: <b>{active?.minor?.length || 0}</b></div>
                </div>
                <a
                  href={resolveUrl(active?.screenshot_url)}
                  target="_blank"
                  rel="noreferrer"
                  className="ui-issues-open"
                >
                  Open full image
                </a>
              </div>
            </div>

            <SeveritySection title="Critical" items={active?.critical} />
            <SeveritySection title="Moderate" items={active?.moderate} />
            <SeveritySection title="Minor" items={active?.minor} />
          </div>
        </div>
      )}
    </div>
  );
}