import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  Upload, Play, Download, Check, AlertCircle, Plus, Trash2,
  Settings, Activity, BarChart2, Terminal, ChevronDown, ChevronRight,
  Zap, Clock, Users, Globe, ArrowUp, ArrowDown, Code2, Layers,
  AlertTriangle,
} from 'lucide-react';

const API_URL = 'http://localhost:8000';
const WS_URL = 'ws://localhost:8000/ws/test-status';

const ts = () => {
  const n = new Date();
  return `${String(n.getHours()).padStart(2, '0')}:${String(n.getMinutes()).padStart(2, '0')}:${String(n.getSeconds()).padStart(2, '0')}.${String(n.getMilliseconds()).padStart(3, '0')}`;
};

// ─── Constants ───────────────────────────────────────────────────────────────
const STAGE_TYPES = {
  rampUp: { label: 'Ramp Up', color: '#16a34a', bg: '#dcfce7', icon: '↗' },
  constant: { label: 'Constant', color: '#2563eb', bg: '#dbeafe', icon: '→' },
  rampDown: { label: 'Ramp Down', color: '#d97706', bg: '#fef3c7', icon: '↘' },
  spike: { label: 'Spike', color: '#dc2626', bg: '#fee2e2', icon: '⚡' },
};

const METHOD_META = {
  GET: { color: '#16a34a', bg: '#dcfce7' },
  POST: { color: '#2563eb', bg: '#dbeafe' },
  PUT: { color: '#d97706', bg: '#fef3c7' },
  DELETE: { color: '#dc2626', bg: '#fee2e2' },
  PATCH: { color: '#7c3aed', bg: '#ede9fe' },
  HEAD: { color: '#64748b', bg: '#f1f5f9' },
  OPTIONS: { color: '#0891b2', bg: '#cffafe' },
};

const DEFAULT_STAGES = [
  { id: 1, type: 'rampUp', duration: 30, target: 10 },
  { id: 2, type: 'constant', duration: 60, target: 10 },
  { id: 3, type: 'rampDown', duration: 30, target: 0 },
];

const DEFAULT_ENDPOINTS = [
  { id: 1, method: 'GET', path: '/api/health', name: 'Health Check', enabled: true, weight: 1, expectedStatus: [200], headers: '', body: '' },
];

let nextStageId = 4;
let nextEndpointId = 2;

// ─── Script generation from builder state ───────────────────────────────────
function buildScript(baseUrl, stages, endpoints, requestTimeout) {
  const stagesCode = stages.map(s =>
    `    { duration: '${s.duration}s', target: ${s.target} }, // ${STAGE_TYPES[s.type]?.label || s.type}`
  ).join('\n');

  const activeEps = endpoints.filter(e => e.enabled && e.path);
  const urlParts = activeEps.map((ep, i) => {
    const headersObj = ep.headers ? `, headers: ${ep.headers}` : '';
    const bodyPart = ep.body ? `, body: JSON.stringify(${ep.body})` : '';
    const methodUpper = ep.method.toUpperCase();
    return `  // ${ep.name}
  const res${i} = http.${methodUpper.toLowerCase()}(\`\${BASE_URL}${ep.path}\`${ep.body ? `, JSON.stringify(${ep.body || '{}'})` : ''}${headersObj ? `, { headers: ${ep.headers} }` : ''});
  check(res${i}, {
    '${ep.name} status ${ep.expectedStatus.join('/')}': (r) => [${ep.expectedStatus.join(', ')}].includes(r.status),
  });`;
  }).join('\n\n');

  return `import http from 'k6/http';
import { check, sleep } from 'k6';

// k6 Load Test — generated by k6 Load Studio
// BASE_URL: ${baseUrl}

const BASE_URL = '${baseUrl}';

export const options = {
  stages: [
${stagesCode}
  ],
  thresholds: {
    http_req_duration: ['p(95)<${requestTimeout}'],
    http_req_failed:   ['rate<0.1'],
  },
};

export default function () {
${activeEps.length ? urlParts : '  // No enabled endpoints configured'}

  sleep(1);
}
`;
}

// ─── Parse script back to builder state ─────────────────────────────────────
function parseScript(script) {
  const result = { baseUrl: null, stages: [], endpoints: [], requestTimeout: 10000, errors: [] };

  // base URL
  const urlMatch = script.match(/const\s+BASE_URL\s*=\s*['"`]([^'"`]+)['"`]/);
  if (urlMatch) result.baseUrl = urlMatch[1];

  // stages — match { duration: '30s', target: 10 }
  const stageRegex = /\{\s*duration:\s*['"`](\d+)s['"`]\s*,\s*target:\s*(\d+)\s*\}(?:[^/\n]*\/\/\s*(\w[\w\s]*))?/g;
  let sm; let stageIdCounter = 1;
  while ((sm = stageRegex.exec(script)) !== null) {
    const duration = parseInt(sm[1]);
    const target = parseInt(sm[2]);
    const label = (sm[3] || '').trim().toLowerCase();
    let type = 'constant';
    if (label.includes('ramp up') || label.includes('rampup')) type = 'rampUp';
    else if (label.includes('ramp down') || label.includes('rampdown')) type = 'rampDown';
    else if (label.includes('spike')) type = 'spike';
    else {
      // Infer from values: if target increases = rampUp, decreases = rampDown
      const prev = result.stages[result.stages.length - 1];
      if (prev) {
        if (target > prev.target) type = 'rampUp';
        else if (target < prev.target) type = 'rampDown';
      }
    }
    result.stages.push({ id: stageIdCounter++, type, duration, target });
  }

  // timeout from thresholds
  const tMatch = script.match(/http_req_duration.*?p\(95\)<(\d+)/);
  if (tMatch) result.requestTimeout = parseInt(tMatch[1]);

  // endpoints — parse http.METHOD(...) calls
  const epRegex = /\/\/\s*(.+?)\n\s*const\s+\w+\s*=\s*http\.(\w+)\(`[^`]*\$\{BASE_URL\}([^`]+)`/g;
  let em; let epIdCounter = 1;
  while ((em = epRegex.exec(script)) !== null) {
    const name = em[1].trim();
    const method = em[2].toUpperCase();
    const path = em[3].trim();
    // find expected status
    const checkRegex = new RegExp(`${name}[^\\[]+\\[([\\d,\\s]+)\\]`);
    const cm = script.match(checkRegex);
    const expectedStatus = cm
      ? cm[1].split(',').map(s => parseInt(s.trim())).filter(Boolean)
      : [200];
    result.endpoints.push({
      id: epIdCounter++, method, path, name, enabled: true,
      weight: 1, expectedStatus, headers: '', body: '',
    });
  }

  if (result.stages.length === 0) result.errors.push('Could not parse stages — check stage format');
  if (result.endpoints.length === 0 && !/No enabled endpoints/.test(script))
    result.errors.push('Could not parse endpoints — check http.method() calls');

  return result;
}

// ─── Main component ──────────────────────────────────────────────────────────
export default function APIBatchTester() {
  const [baseUrl, setBaseUrl] = useState('http://localhost:3000');
  const [stages, setStages] = useState(DEFAULT_STAGES);
  const [endpoints, setEndpoints] = useState(DEFAULT_ENDPOINTS);
  const [results, setResults] = useState([]);
  const [summary, setSummary] = useState(null);
  const [logs, setLogs] = useState([]);
  const [running, setRunning] = useState(false);
  const [activeTab, setActiveTab] = useState('scenario');
  const [scenarioMode, setScenarioMode] = useState('builder'); // 'builder' | 'script'
  const [requestTimeout, setRequestTimeout] = useState(10000);
  const [iframeUrl, setIframeUrl] = useState('');
  const [tempIframeUrl, setTempIframeUrl] = useState('http://localhost:8000/static/grafana.html');
  const [showIframeSet, setShowIframeSet] = useState(false);
  const [expandedEp, setExpandedEp] = useState(null);
  const [script, setScript] = useState('');
  const [parseErrors, setParseErrors] = useState([]);
  const [scriptDirty, setScriptDirty] = useState(false); // script edited by user, not yet synced
  const logBodyRef = useRef(null);
  const wsRef = useRef(null);
  const fileInputRef = useRef(null);
  const scriptRef = useRef(null);
  const [savedScripts, setSavedScripts] = useState([]);
  const [selectedScriptId, setSelectedScriptId] = useState(null);

  const [runHistory, setRunHistory] = useState([]);
  const [selectedRun, setSelectedRun] = useState(null);

  const [runLogs, setRunLogs] = useState([]);
  const [runMetrics, setRunMetrics] = useState([]);

  const [scriptName, setScriptName] = useState('');
  const [scriptDescription, setScriptDescription] = useState('');

  const buildIframeUrl = (isRunning) => {
    return `http://localhost:3000/d/YOUR_DASHBOARD_ID/YOUR_DASHBOARD_NAME?orgId=1&refresh=${isRunning ? '2s' : '10s'}&from=now-5m&to=now&kiosk&_t=${Date.now()}`;
  };  // Keep script in sync whenever builder state changes (only if in builder mode)

  useEffect(() => {
    setIframeUrl(buildIframeUrl(false));
  }, []);
  useEffect(() => {
    if (scenarioMode === 'builder') {
      setScript(buildScript(baseUrl, stages, endpoints, requestTimeout));
      setScriptDirty(false);
    }
  }, [baseUrl, stages, endpoints, requestTimeout, scenarioMode]);

  // Auto-scroll logs in monitoring
  useEffect(() => {
    if (logBodyRef.current) logBodyRef.current.scrollTop = logBodyRef.current.scrollHeight;
  }, [logs]);

  // WebSocket
  useEffect(() => {
    wsRef.current = new WebSocket(WS_URL);
    wsRef.current.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === 'BATCH_API_TEST') {
        const { action, total, index, result, summary: ns } = data.payload;
        if (action === 'test_start') {
          setRunning(true);
          setActiveTab('monitoring'); // auto open monitoring
          setIframeUrl(buildIframeUrl(true));
        } else if (action === 'test_progress') {
          setResults(prev => { const u = [...prev]; u[index - 1] = result; return u; });
          appendLog(result.passed ? 'SUCCESS' : 'FAILED',
            `[${index}/${total}] ${result.method} ${result.endpoint} → ${result.status} (${result.duration}ms)`);
        } else if (action === 'test_complete') {
          setRunning(false);
          setIframeUrl(buildIframeUrl(false));
        }
      }
    };
    return () => { if (wsRef.current) wsRef.current.close(); };
  }, []);

  const appendLog = (level, msg) =>
    setLogs(prev => [{ level, msg, time: ts() }, ...prev.slice(0, 499)]);

  // ── Toggle between builder ↔ script ──────────────────────────────────────
  const switchToScript = () => {
    // Always regenerate from current builder state when switching to script
    setScript(buildScript(baseUrl, stages, endpoints, requestTimeout));
    setScriptDirty(false);
    setParseErrors([]);
    setScenarioMode('script');
  };

  const switchToBuilder = () => {
    // Parse current script and update builder state
    const parsed = parseScript(script);
    setParseErrors(parsed.errors);
    if (parsed.baseUrl) setBaseUrl(parsed.baseUrl);
    if (parsed.stages.length) { setStages(parsed.stages); nextStageId = parsed.stages.length + 1; }
    if (parsed.endpoints.length) { setEndpoints(parsed.endpoints); nextEndpointId = parsed.endpoints.length + 1; }
    if (parsed.requestTimeout) setRequestTimeout(parsed.requestTimeout);
    setScriptDirty(false);
    setScenarioMode('builder');
  };

  const handleScriptChange = (val) => {
    setScript(val);
    setScriptDirty(true);
  };

  // ── Apply script changes to builder live (debounced) ─────────────────────
  const applyScriptToBuilder = useCallback(() => {
    if (!scriptDirty) return;
    const parsed = parseScript(script);
    setParseErrors(parsed.errors);
    if (parsed.baseUrl) setBaseUrl(parsed.baseUrl);
    if (parsed.stages.length) { setStages(parsed.stages); nextStageId = parsed.stages.length + 1; }
    if (parsed.endpoints.length) { setEndpoints(parsed.endpoints); nextEndpointId = parsed.endpoints.length + 1; }
    if (parsed.requestTimeout) setRequestTimeout(parsed.requestTimeout);
    setScriptDirty(false);
  }, [script, scriptDirty]);

  // ── Stage helpers ─────────────────────────────────────────────────────────
  const addStage = (type) => setStages(p => [...p, { id: nextStageId++, type, duration: 30, target: 10 }]);
  const updateStage = (id, f, v) => setStages(p => p.map(s => s.id === id ? { ...s, [f]: v } : s));
  const removeStage = (id) => setStages(p => p.filter(s => s.id !== id));
  const moveStage = (id, dir) => setStages(prev => {
    const idx = prev.findIndex(s => s.id === id), next = [...prev], swap = idx + dir;
    if (swap < 0 || swap >= next.length) return prev;
    [next[idx], next[swap]] = [next[swap], next[idx]]; return next;
  });

  // ── Endpoint helpers ──────────────────────────────────────────────────────
  const addEndpoint = () => setEndpoints(p => [...p, { id: nextEndpointId++, method: 'GET', path: '', name: 'New Endpoint', enabled: true, weight: 1, expectedStatus: [200], headers: '', body: '' }]);
  const updateEndpoint = (id, f, v) => setEndpoints(p => p.map(e => e.id === id ? { ...e, [f]: v } : e));
  const removeEndpoint = (id) => setEndpoints(p => p.filter(e => e.id !== id));

  // ── File import ───────────────────────────────────────────────────────────
  const handleFileSelect = async (e) => {
    const file = e.target.files?.[0]; if (!file) return;
    appendLog('INFO', `Parsing ${file.name}…`);
    const fd = new FormData(); fd.append('file', file);
    try {
      const res = await fetch(`${API_URL}/api/batch/parse-excel`, { method: 'POST', body: fd });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      const imp = (data.apis || []).map((a, i) => ({
        id: nextEndpointId++, method: a.method || 'GET', path: a.endpoint || '',
        name: a.api_name || `API ${i + 1}`, enabled: true, weight: 1,
        expectedStatus: a.expected_status || [200], headers: '', body: '',
      }));
      setEndpoints(p => [...p, ...imp]);
      appendLog('SUCCESS', `Imported ${imp.length} endpoints`);
    } catch (err) { appendLog('FAILED', `Parse error: ${err.message}`); }
  };

  // ── Run tests ─────────────────────────────────────────────────────────────
  const handleRunTests = async () => {

    if (!selectedScriptId) {

      appendLog(
        "FAILED",
        "Please select or save a script first"
      );

      return;
    }

    try {

      setRunning(true);

      appendLog(
        "INFO",
        `Starting test: ${scriptName}`
      );

      const res = await fetch(
        `${API_URL}/api-testing/runs/start`,
        {

          method: 'POST',

          headers: {
            'Content-Type': 'application/json'
          },

          body: JSON.stringify({

            scriptId: selectedScriptId,

            scriptName: scriptName

          })
        }
      );

      if (!res.ok) {

        throw new Error(
          await res.text()
        );
      }

      const data = await res.json();

      appendLog(
        "SUCCESS",
        "Test execution started"
      );

      console.log(data);

    } catch (err) {

      appendLog(
        "FAILED",
        err.message
      );

    } finally {

      setRunning(false);
    }
  };

  const handleDownloadSample = async () => {
    try {
      const res = await fetch(`${API_URL}/api/batch/sample-excel`);
      if (!res.ok) throw new Error(await res.text());
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      Object.assign(document.createElement('a'), { href: url, download: 'api_batch_template.xlsx' }).click();
      URL.revokeObjectURL(url);
      appendLog('SUCCESS', 'Template downloaded');
    } catch (err) { appendLog('FAILED', `Download failed: ${err.message}`); }
  };

  const handleExportResults = () => {
    if (!results.length) { appendLog('FAILED', 'No results to export'); return; }
    const csv = [
      ['API Name', 'Method', 'Endpoint', 'Status', 'Expected', 'Passed', 'Duration', 'Error', 'Timestamp'].join(','),
      ...results.map(r => [`"${r.api_name}"`, r.method, `"${r.endpoint}"`, r.status || 'N/A', r.expected.join(';'), r.passed ? 'YES' : 'NO', r.duration, r.error ? `"${r.error}"` : '', r.timestamp].join(',')),
    ].join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
    Object.assign(document.createElement('a'), { href: url, download: `load_test_${Date.now()}.csv` }).click();
    URL.revokeObjectURL(url);
    appendLog('SUCCESS', 'Results exported');
  };

  // ── Load profile chart ────────────────────────────────────────────────────
  const totalDuration = stages.reduce((s, x) => s + (Number(x.duration) || 0), 0) || 1;
  const maxVUs = Math.max(...stages.map(s => Number(s.target) || 0), 1);

  const buildPath = () => {
    if (!stages.length) return '';
    const W = 480, H = 72, pad = 4;
    const pts = [{ x: pad, y: H - pad }];
    let elapsed = 0;
    stages.forEach(s => {
      const x2 = pad + ((elapsed + s.duration) / totalDuration) * (W - pad * 2);
      const yTgt = pad + (1 - s.target / maxVUs) * (H - pad * 2);
      const yPrev = pts[pts.length - 1].y;
      if (s.type === 'constant') pts.push({ x: pad + (elapsed / totalDuration) * (W - pad * 2), y: yPrev });
      pts.push({ x: x2, y: yTgt });
      elapsed += s.duration;
    });
    pts.push({ x: W - pad, y: H - pad });
    return pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ') + ' Z';
  };

  // ── Script syntax highlight (lightweight) ────────────────────────────────
  // We use a plain textarea with line numbers overlay for simplicity
  const scriptLines = script.split('\n');

  // ── Tabs ──────────────────────────────────────────────────────────────────
  const TABS = [
    { id: 'scenario', label: 'Load Scenario', icon: <BarChart2 size={13} /> },
    { id: 'results', label: 'Results', icon: <Activity size={13} />, disabled: !results.length },
    { id: 'monitoring', label: 'Monitoring', icon: <Zap size={13} /> },
  ];

  const handleSaveScript = async () => {
    try {

      const payload = {
        name: scriptName,
        // description: scriptDescription,

        script: script,

        config: {
          baseUrl,
          stages,
          endpoints,
          requestTimeout
        }
      };

      const res = await fetch(
        `${API_URL}/api-testing/scripts/create`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(payload)
        }
      );

      const data = await res.json();

      appendLog("SUCCESS", `Script saved`);

      loadScripts();

    } catch (err) {

      appendLog(
        "FAILED",
        `Save failed: ${err.message}`
      );
    }
  };

  const loadScripts = async () => {
    const res = await fetch(
      `${API_URL}/api-testing/scripts`
    );
    const data = await res.json();
    console.log(data)

    setSavedScripts(data.scripts || []);
  };

  const loadScript = async (id) => {
    const res = await fetch(
      `${API_URL}/api-testing/scripts/${id}`
    );
    const data = await res.json();
    setSelectedScriptId(id);
    setScript(data.script);
    setBaseUrl(data.config.baseUrl);
    setStages(data.config.stages);
    setEndpoints(data.config.endpoints);
    setScriptName(data.name);
    setRequestTimeout(
      data.config.requestTimeout
    );

    appendLog(
      "INFO",
      `Loaded script: ${data.name}`
    );
  };

  useEffect(() => {
    loadScripts();
  }, []);

  // ═══════════════════════════════════════════════════════════════════════════
  return (
    <div style={S.root}>

      {/* ─── HEADER ─── */}
      <header style={S.header}>
        <div style={S.headerLeft}>
          <div style={S.logo}>
            <div style={S.logoIcon}><BarChart2 size={15} color="#fff" /></div>
            <div>
              <div style={S.logoTitle}>Load Studio</div>
              <div style={S.logoSub}>API Performance Testing</div>
            </div>
          </div>
          <div style={{ ...S.badge, ...(running ? { background: '#dcfce7', color: '#16a34a', borderColor: '#bbf7d0' } : {}) }}>
            <span style={{ ...S.dot, background: running ? '#16a34a' : '#94a3b8' }} />
            {running ? 'RUNNING' : 'IDLE'}
          </div>
        </div>
        <div style={S.headerRight}>
          <select
            value={selectedScriptId || ''}
            onChange={(e) => {

              const id = e.target.value;

              setSelectedScriptId(id);
              console.log("Selected ID:", id);

              if (id) {
                loadScript(id);
              }
            }}

            style={{
              padding: '8px',
              borderRadius: '8px',
              border: '1px solid #ccc',
              minWidth: '220px'
            }}
          >
            <option value="">
              Select Saved Script
            </option>
            {savedScripts.map(script => (
              <option
                key={script.id}
                value={script.id}
              >
                {script.name}
              </option>
            ))}
          </select>
          <div style={S.urlBar}>
            <Globe size={13} color="#94a3b8" />
            <input style={S.urlInput} value={baseUrl}
              onChange={e => setBaseUrl(e.target.value)}
              placeholder="https://your-api.com" disabled={running} />
          </div>
          <button style={{ ...S.btnPrimary, opacity: running ? .5 : 1 }}
            onClick={handleRunTests} disabled={running}>
            <Play size={13} fill={running ? 'transparent' : '#fff'} />
            {running ? 'Running…' : 'Run Test'}
          </button>
        </div>
      </header>

      {/* ─── TAB BAR ─── */}
      <div style={S.tabBar}>
        {TABS.map(t => (
          <button key={t.id}
            style={{ ...S.tab, ...(activeTab === t.id ? S.tabActive : {}), ...(t.disabled ? { opacity: .35, cursor: 'not-allowed' } : {}) }}
            onClick={() => !t.disabled && setActiveTab(t.id)}>
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {/* ─── BODY ─── */}
      <div style={S.body}>

        {/* ══ SCENARIO TAB ══ */}
        {activeTab === 'scenario' && (
          <div style={S.scenarioWrap}>

            {/* Builder / Script toggle bar */}
            <div style={S.toggleBar}>
              <div style={S.toggleGroup}>
                <button
                  style={{ ...S.toggleBtn, ...(scenarioMode === 'builder' ? S.toggleActive : {}) }}
                  onClick={() => scenarioMode === 'script' ? switchToBuilder() : null}>
                  <Layers size={13} /> Builder
                </button>
                <button
                  style={{ ...S.toggleBtn, ...(scenarioMode === 'script' ? S.toggleActive : {}) }}
                  onClick={() => scenarioMode === 'builder' ? switchToScript() : null}>
                  <Code2 size={13} /> Script
                </button>
              </div>
              {scenarioMode === 'script' && (
                <div style={S.toggleHint}>
                  <span style={{ color: '#94a3b8', fontSize: 11 }}>
                    Edit the script below. Changes sync back to Builder automatically when you switch.
                  </span>
                  <button style={S.syncBtn} onClick={applyScriptToBuilder} disabled={!scriptDirty}>
                    ↺ Sync to Builder{scriptDirty ? ' *' : ''}
                  </button>
                </div>
              )}
              <input
                type="text"
                placeholder="Script Name"
                value={scriptName}
                onChange={(e) =>
                  setScriptName(e.target.value)
                }

                style={{
                  padding: '8px 12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '8px',
                  minWidth: '220px'
                }}
              />
              <button onClick={handleSaveScript}>
                Save Script
              </button>
              {scenarioMode === 'builder' && (
                <span style={{ color: '#94a3b8', fontSize: 11 }}>
                  Configure visually — script auto-updates as you edit
                </span>
              )}
            </div>

            {/* Parse errors */}
            {parseErrors.length > 0 && (
              <div style={S.errorBanner}>
                <AlertTriangle size={13} />
                <span>Parse warnings: {parseErrors.join(' · ')}</span>
              </div>
            )}

            {/* ── BUILDER MODE ── */}
            {scenarioMode === 'builder' && (
              <div style={S.twoCol}>

                {/* LEFT — Load Profile */}
                <div style={S.panel}>
                  <div style={S.panelHead}>
                    <span style={S.panelTitle}><BarChart2 size={14} color="#2563eb" /> Load Profile</span>
                    <div style={S.headActions}>
                      {Object.entries(STAGE_TYPES).map(([type, info]) => (
                        <button key={type}
                          style={{ ...S.tagBtn, color: info.color, background: info.bg, borderColor: info.color + '55' }}
                          onClick={() => addStage(type)}>
                          <Plus size={10} /> {info.label}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Chart */}
                  <div style={S.chartBox}>
                    <svg viewBox="0 0 488 80" style={{ width: '100%', height: 80, display: 'block' }} preserveAspectRatio="none">
                      <defs>
                        <linearGradient id="profileGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#2563eb" stopOpacity=".15" />
                          <stop offset="100%" stopColor="#2563eb" stopOpacity=".02" />
                        </linearGradient>
                      </defs>
                      {[.25, .5, .75].map(f => (
                        <line key={f} x1="4" y1={4 + (1 - f) * 72} x2="484" y2={4 + (1 - f) * 72}
                          stroke="#f1f5f9" strokeWidth="1" />
                      ))}
                      <path d={buildPath()} fill="url(#profileGrad)" stroke="#2563eb" strokeWidth="1.8" strokeLinejoin="round" />
                      {(() => {
                        let el = 0;
                        return stages.map(s => {
                          const cx = 4 + ((el + s.duration / 2) / totalDuration) * 480;
                          el += s.duration;
                          return (
                            <text key={s.id} x={cx} y="44" textAnchor="middle"
                              fill={STAGE_TYPES[s.type].color} fontSize="8.5"
                              fontFamily="system-ui" fontWeight="700">
                              {STAGE_TYPES[s.type].label}
                            </text>
                          );
                        });
                      })()}
                    </svg>
                    <div style={S.chartMeta}>
                      <span style={S.metaChip}><Clock size={11} /> {totalDuration}s total</span>
                      <span style={S.metaChip}><Users size={11} /> {maxVUs} peak VUs</span>
                    </div>
                  </div>

                  {/* Stage rows */}
                  <div style={{ padding: '8px 14px 4px' }}>
                    {stages.map((s, idx) => (
                      <div key={s.id} style={{ ...S.stageRow, borderLeftColor: STAGE_TYPES[s.type].color }}>
                        <div style={{ ...S.stageTag, color: STAGE_TYPES[s.type].color, background: STAGE_TYPES[s.type].bg }}>
                          {STAGE_TYPES[s.type].icon} {STAGE_TYPES[s.type].label}
                        </div>
                        <label style={S.fGroup}>
                          <span style={S.fLabel}>Duration (s)</span>
                          <input style={S.numInput} type="number" min="1" value={s.duration}
                            onChange={e => updateStage(s.id, 'duration', Number(e.target.value))} />
                        </label>
                        <label style={S.fGroup}>
                          <span style={S.fLabel}>Target VUs</span>
                          <input style={S.numInput} type="number" min="0" value={s.target}
                            onChange={e => updateStage(s.id, 'target', Number(e.target.value))} />
                        </label>
                        <div style={S.rowBtns}>
                          <button style={S.iconBtn} onClick={() => moveStage(s.id, -1)} disabled={idx === 0}><ArrowUp size={11} /></button>
                          <button style={S.iconBtn} onClick={() => moveStage(s.id, 1)} disabled={idx === stages.length - 1}><ArrowDown size={11} /></button>
                          <button style={{ ...S.iconBtn, ...S.iconDanger }} onClick={() => removeStage(s.id)}><Trash2 size={11} /></button>
                        </div>
                      </div>
                    ))}
                    {stages.length === 0 && <div style={S.empty}>No stages — add one above</div>}
                  </div>

                  {/* Options */}
                  <div style={S.optRow}>
                    <label style={S.fGroup}>
                      <span style={S.fLabel}><Clock size={10} /> Request Timeout (ms)</span>
                      <input style={{ ...S.numInput, width: 110 }} type="number" min="1000" value={requestTimeout}
                        onChange={e => setRequestTimeout(Number(e.target.value))} />
                    </label>
                  </div>
                </div>

                {/* RIGHT — Endpoints */}
                <div style={S.panel}>
                  <div style={S.panelHead}>
                    <span style={S.panelTitle}>
                      <Globe size={14} color="#2563eb" /> Endpoints
                      <span style={S.countPill}>{endpoints.filter(e => e.enabled).length} active</span>
                    </span>
                    <div style={S.headActions}>
                      <input ref={fileInputRef} type="file" accept=".xlsx,.xls" style={{ display: 'none' }} onChange={handleFileSelect} />
                      <button style={S.outBtn} onClick={() => fileInputRef.current?.click()}><Upload size={10} /> Import</button>
                      <button style={S.outBtn} onClick={handleDownloadSample}><Download size={10} /> Template</button>
                      <button style={{ ...S.outBtn, ...S.outPrimary }} onClick={addEndpoint}><Plus size={10} /> Add</button>
                    </div>
                  </div>

                  <div style={S.epHead}>
                    <span style={{ width: 26 }} />
                    <span style={{ width: 68 }}>Method</span>
                    <span style={{ flex: 1 }}>Path</span>
                    <span style={{ width: 120 }}>Name</span>
                    <span style={{ width: 66 }}>Status</span>
                    <span style={{ width: 44 }} />
                  </div>

                  <div style={{ overflowY: 'auto', maxHeight: 420 }}>
                    {endpoints.map(ep => (
                      <div key={ep.id} style={S.epGroup}>
                        <div style={S.epRow} onClick={() => setExpandedEp(expandedEp === ep.id ? null : ep.id)}>
                          <input type="checkbox" checked={ep.enabled}
                            style={{ accentColor: '#2563eb', cursor: 'pointer', width: 16, flexShrink: 0 }}
                            onChange={e => { e.stopPropagation(); updateEndpoint(ep.id, 'enabled', e.target.checked); }} />
                          <select
                            style={{ ...S.methodBadge, color: METHOD_META[ep.method]?.color, background: METHOD_META[ep.method]?.bg, borderColor: (METHOD_META[ep.method]?.color || '#94a3b8') + '55' }}
                            value={ep.method}
                            onChange={e => { e.stopPropagation(); updateEndpoint(ep.id, 'method', e.target.value); }}
                            onClick={e => e.stopPropagation()}>
                            {Object.keys(METHOD_META).map(m => <option key={m}>{m}</option>)}
                          </select>
                          <input style={S.pathInput} value={ep.path} placeholder="/api/endpoint"
                            onChange={e => updateEndpoint(ep.id, 'path', e.target.value)}
                            onClick={e => e.stopPropagation()} />
                          <input style={S.nameInput} value={ep.name} placeholder="Name"
                            onChange={e => updateEndpoint(ep.id, 'name', e.target.value)}
                            onClick={e => e.stopPropagation()} />
                          <input style={S.statusInput} value={ep.expectedStatus.join(',')} placeholder="200"
                            onChange={e => updateEndpoint(ep.id, 'expectedStatus', e.target.value.split(',').map(x => parseInt(x.trim())).filter(Boolean))}
                            onClick={e => e.stopPropagation()} />
                          <div style={{ display: 'flex', alignItems: 'center', gap: 2, flexShrink: 0 }}>
                            <button style={{ ...S.iconBtn, ...S.iconDanger }} onClick={e => { e.stopPropagation(); removeEndpoint(ep.id); }}><Trash2 size={11} /></button>
                            <span style={{ color: '#94a3b8', display: 'flex' }}>
                              {expandedEp === ep.id ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                            </span>
                          </div>
                        </div>
                        {expandedEp === ep.id && (
                          <div style={S.epExpanded}>
                            <label style={S.expLabel}>
                              <span>Headers (JSON)</span>
                              <textarea style={S.codeArea} rows={3} value={ep.headers}
                                placeholder={'{"Authorization":"Bearer token"}'}
                                onChange={e => updateEndpoint(ep.id, 'headers', e.target.value)} />
                            </label>
                            <label style={S.expLabel}>
                              <span>Request Body (JSON)</span>
                              <textarea style={S.codeArea} rows={3} value={ep.body}
                                placeholder={'{"key":"value"}'}
                                onChange={e => updateEndpoint(ep.id, 'body', e.target.value)} />
                            </label>
                            <label style={{ ...S.expLabel, maxWidth: 130 }}>
                              <span>Weight</span>
                              <input style={S.numInput} type="number" min="1" value={ep.weight}
                                onChange={e => updateEndpoint(ep.id, 'weight', Number(e.target.value))} />
                            </label>
                          </div>
                        )}
                      </div>
                    ))}
                    {endpoints.length === 0 && <div style={S.empty}>No endpoints — add or import above</div>}
                  </div>
                </div>
              </div>
            )}

            {/* ── SCRIPT MODE ── */}
            {scenarioMode === 'script' && (
              <div style={S.scriptWrap}>
                <div style={S.scriptPanel}>
                  {/* Live preview mini-panels (read-only) */}
                  <div style={S.scriptSidebar}>
                    <div style={S.sideCard}>
                      <div style={S.sideCardHead}>
                        <BarChart2 size={12} color="#2563eb" />
                        <span>Stages ({stages.length})</span>
                      </div>
                      {stages.map((s, i) => (
                        <div key={i} style={S.sideRow}>
                          <span style={{ ...S.sideTag, color: STAGE_TYPES[s.type]?.color, background: STAGE_TYPES[s.type]?.bg }}>
                            {STAGE_TYPES[s.type]?.icon}
                          </span>
                          <span style={S.sideVal}>{STAGE_TYPES[s.type]?.label}</span>
                          <span style={S.sideMeta}>{s.duration}s → {s.target} VUs</span>
                        </div>
                      ))}
                      {stages.length === 0 && <div style={S.sideEmpty}>—</div>}
                    </div>

                    <div style={S.sideCard}>
                      <div style={S.sideCardHead}>
                        <Globe size={12} color="#2563eb" />
                        <span>Endpoints ({endpoints.filter(e => e.enabled).length})</span>
                      </div>
                      {endpoints.filter(e => e.enabled).map((ep, i) => (
                        <div key={i} style={S.sideRow}>
                          <span style={{ ...S.sideTag, color: METHOD_META[ep.method]?.color, background: METHOD_META[ep.method]?.bg }}>
                            {ep.method.slice(0, 3)}
                          </span>
                          <span style={{ ...S.sideVal, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{ep.path || '—'}</span>
                        </div>
                      ))}
                      {endpoints.filter(e => e.enabled).length === 0 && <div style={S.sideEmpty}>—</div>}
                    </div>

                    <div style={S.sideCard}>
                      <div style={S.sideCardHead}>
                        <Clock size={12} color="#2563eb" />
                        <span>Summary</span>
                      </div>
                      <div style={S.sideRow}>
                        <span style={S.sideKey}>Total duration</span>
                        <span style={S.sideVal}>{totalDuration}s</span>
                      </div>
                      <div style={S.sideRow}>
                        <span style={S.sideKey}>Peak VUs</span>
                        <span style={S.sideVal}>{maxVUs}</span>
                      </div>
                      <div style={S.sideRow}>
                        <span style={S.sideKey}>Timeout</span>
                        <span style={S.sideVal}>{requestTimeout}ms</span>
                      </div>
                      <div style={S.sideRow}>
                        <span style={S.sideKey}>Base URL</span>
                        <span style={{ ...S.sideVal, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 10 }}>{baseUrl}</span>
                      </div>
                    </div>

                    {scriptDirty && (
                      <div style={S.dirtyBadge}>
                        <AlertTriangle size={11} />
                        Script has unsaved changes — click "Sync to Builder" to update the visual panels.
                      </div>
                    )}
                  </div>

                  {/* Code editor */}
                  <div style={S.editorWrap}>
                    <div style={S.editorHead}>
                      <span style={{ fontSize: 11, color: '#64748b', fontFamily: 'monospace' }}>
                        test-script.js
                      </span>
                      <div style={{ display: 'flex', gap: 6 }}>
                        {scriptDirty && (
                          <span style={{ fontSize: 10, color: '#d97706', background: '#fef3c7', padding: '1px 7px', borderRadius: 8, border: '1px solid #fde68a' }}>
                            ● unsaved
                          </span>
                        )}
                        <button style={S.outBtn} onClick={() => {
                          const url = URL.createObjectURL(new Blob([script], { type: 'text/javascript' }));
                          Object.assign(document.createElement('a'), { href: url, download: 'test-script.js' }).click();
                          URL.revokeObjectURL(url);
                        }}>
                          <Download size={10} /> Download
                        </button>
                      </div>
                    </div>

                    {/* Line-numbered editor */}
                    <div style={S.editorBody}>
                      <div style={S.lineNums} aria-hidden="true">
                        {scriptLines.map((_, i) => (
                          <div key={i} style={S.lineNum}>{i + 1}</div>
                        ))}
                      </div>
                      <textarea
                        ref={scriptRef}
                        style={S.codeEditor}
                        value={script}
                        onChange={e => handleScriptChange(e.target.value)}
                        spellCheck={false}
                        autoComplete="off"
                        autoCorrect="off"
                        autoCapitalize="off"
                      />
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ══ RESULTS TAB ══ */}
        {activeTab === 'results' && (
          <div style={{ padding: 16, flex: 1, overflow: 'auto' }}>
            <div style={S.panel}>
              <div style={S.panelHead}>
                <span style={S.panelTitle}><Activity size={14} color="#2563eb" /> Test Results</span>
                <div style={S.headActions}>
                  <button style={S.outBtn} onClick={handleExportResults}><Download size={10} /> Export CSV</button>
                  <button style={S.outBtn} onClick={() => { setActiveTab('scenario'); setResults([]); setSummary(null); }}>
                    <Plus size={10} /> New Test
                  </button>
                </div>
              </div>

              {summary && (
                <div style={S.metricRow}>
                  {[
                    { label: 'PASSED', val: summary.passed, color: '#16a34a', bg: '#dcfce7' },
                    { label: 'FAILED', val: summary.failed, color: '#dc2626', bg: '#fee2e2' },
                    { label: 'TOTAL', val: summary.total, color: '#475569', bg: '#f1f5f9' },
                    { label: 'DURATION', val: `${summary.duration}ms`, color: '#2563eb', bg: '#dbeafe' },
                    { label: 'PASS RATE', val: `${Math.round(summary.passed / summary.total * 100)}%`, color: '#7c3aed', bg: '#ede9fe' },
                  ].map(m => (
                    <div key={m.label} style={{ ...S.metricCard, background: m.bg }}>
                      <div style={{ ...S.metricVal, color: m.color }}>{m.val}</div>
                      <div style={S.metricLbl}>{m.label}</div>
                    </div>
                  ))}
                </div>
              )}

              <div style={S.rtHead}>
                <span style={{ width: 28 }} />
                <span style={{ width: 70 }}>Method</span>
                <span style={{ flex: 1 }}>Endpoint</span>
                <span style={{ width: 140 }}>Name</span>
                <span style={{ width: 56 }}>HTTP</span>
                <span style={{ width: 80 }}>Duration</span>
              </div>
              {results.map((r, i) => (
                <div key={i} style={{ ...S.rtRow, borderLeftColor: r.passed ? '#16a34a' : '#dc2626' }}>
                  <span style={{ width: 28, color: r.passed ? '#16a34a' : '#dc2626', display: 'flex', alignItems: 'center' }}>
                    {r.passed ? <Check size={13} /> : <AlertCircle size={13} />}
                  </span>
                  <span style={{ width: 70 }}>
                    <span style={{ ...S.mPill, color: METHOD_META[r.method]?.color, background: METHOD_META[r.method]?.bg }}>{r.method}</span>
                  </span>
                  <span style={{ flex: 1, fontSize: 11, color: '#64748b', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.endpoint}</span>
                  <span style={{ width: 140, fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.api_name}</span>
                  <span style={{ width: 56, fontSize: 12, fontWeight: 600, color: r.status >= 400 ? '#dc2626' : '#16a34a' }}>{r.status || 'ERR'}</span>
                  <span style={{ width: 80, fontSize: 11, color: '#94a3b8' }}>{r.duration}ms</span>
                </div>
              ))}
              {results.length === 0 && <div style={S.empty}>No results yet</div>}
            </div>
          </div>
        )}

        {/* ══ MONITORING TAB ══ */}
        {activeTab === 'monitoring' && (
          <div style={S.monitorWrap}>
            {/* Dashboard iframe */}
            <div style={{ ...S.panel, flex: 1, padding: 0, display: 'flex', flexDirection: 'column' }}>
              <div style={S.panelHead}>
                <span style={S.panelTitle}><Zap size={14} color="#2563eb" /> Live Dashboard</span>
                {/* <button style={S.outBtn} onClick={() => setShowIframeSet(v => !v)}><Settings size={10} /> Configure</button> */}
              </div>
              {/* {showIframeSet && (
                <div style={{ display: 'flex', gap: 8, padding: '10px 14px', borderBottom: '1px solid #e2e8f0', alignItems: 'center', background: '#f8fafc' }}>
                  <input style={{ flex: 1, background: '#fff', border: '1px solid #e2e8f0', borderRadius: 5, padding: '5px 10px', color: '#1e293b', fontFamily: 'inherit', fontSize: 12, outline: 'none' }}
                    value={tempIframeUrl} onChange={e => setTempIframeUrl(e.target.value)} placeholder="Dashboard URL" />
                  <button style={S.btnPrimary} onClick={() => {
                    setIframeUrl(tempIframeUrl + `&_t=${Date.now()}`);
                    setShowIframeSet(false);
                  }}>Apply</button>
                  <button style={S.outBtn} onClick={() => setShowIframeSet(false)}>Cancel</button>
                </div>
              )} */}
              {/* <iframe src="http://localhost:3000/d/adlxqpf/dashboard-1?orgId=1&from=2026-04-28T01:00:34.691Z&to=2026-04-28T01:05:55.562Z&timezone=browser" width="100%" height="100%" frameborder="0"></iframe> */}
              {/* <iframe src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777338034691&to=1777338355562&timezone=browser&panelId=panel-5" width="auto" height="100" frameborder="0"></iframe>
              <iframe src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777338034691&to=1777338355562&timezone=browser&panelId=panel-4" width="auto" height="100" frameborder="0"></iframe>
              <iframe src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777338034691&to=1777338355562&timezone=browser&panelId=panel-2" width="auto" height="100" frameborder="0"></iframe>
              <iframe src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777338034691&to=1777338355562&timezone=browser&panelId=panel-3" width="auto" height="100" frameborder="0"></iframe> */}
              <div
                style={{
                  display: "flex",
                  // gap: "12px",
                  width: "100%",
                  flexWrap: "nowrap",
                }}
              >
                <iframe
                  title="P95 Response Time"
                  src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777746600000&to=1777832999000&timezone=browser&panelId=panel-5"
                  style={{
                    flex: 1,
                    height: "120px",
                    border: "none",
                    // borderRadius: "10px",
                  }}
                />

                <iframe
                  title="Peak RPS"
                  src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777746600000&to=1777832999000&timezone=browser&panelId=panel-4"
                  style={{
                    flex: 1,
                    height: "120px",
                    border: "none",
                    // borderRadius: "10px",
                  }}
                />

                <iframe
                  title="Total Requests"
                  src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777746600000&to=1777832999000&timezone=browser&panelId=panel-2"
                  style={{
                    flex: 1,
                    height: "120px",
                    border: "none",
                    // borderRadius: "10px",
                  }}
                />

                <iframe
                  title="HTTP Failures"
                  src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777746600000&to=1777832999000&timezone=browser&panelId=panel-3"
                  style={{
                    flex: 1,
                    height: "120px",
                    border: "none",
                    // borderRadius: "10px",
                  }}
                />
              </div>
              <iframe src="http://localhost:3000/d-solo/adlxqpf/dashboard-1?orgId=1&from=1777746600000&to=1777832999000&timezone=browser&panelId=panel-1" width="100%" height="100%" frameborder="0"></iframe>
            </div>

            {/* Execution Log — only here */}
            {/* <div style={S.logPanel}>
              <div style={S.logPanelHead}>
                <span style={S.panelTitle}><Terminal size={13} color="#475569" /> Execution Log</span>
                <span style={{ fontSize: 10, color: '#94a3b8' }}>{logs.length} entries</span>
              </div>
              <div style={S.logBody} ref={logBodyRef}>
                {logs.length === 0
                  ? <div style={{ padding: '12px 14px', color: '#cbd5e1', fontSize: 11 }}>No activity yet — run a test to see logs.</div>
                  : logs.map((l, i) => (
                    <div key={i} style={{ ...S.logLine, color: LOG_COLORS[l.level] || '#64748b' }}>
                      <span style={S.logTime}>{l.time}</span>
                      <span style={S.logLvl}>{l.level}</span>
                      <span style={S.logMsg}>{l.msg}</span>
                    </div>
                  ))
                }
              </div>
            </div> */}
          </div>
        )}
      </div>
    </div>
  );
}

const LOG_COLORS = { INFO: '#64748b', SUCCESS: '#16a34a', FAILED: '#dc2626', WARN: '#d97706' };

// ─── Styles ───────────────────────────────────────────────────────────────────
const S = {
  root: {
    fontFamily: "'Inter','Segoe UI',system-ui,sans-serif",
    background: '#f1f5f9',
    color: '#1e293b',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    fontSize: 13,
  },

  // Header
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 20px', background: '#fff', borderBottom: '1px solid #e2e8f0', boxShadow: '0 1px 4px rgba(0,0,0,.06)' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 14 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 10 },
  logo: { display: 'flex', alignItems: 'center', gap: 10 },
  logoIcon: { width: 32, height: 32, borderRadius: 8, background: 'linear-gradient(135deg,#2563eb,#7c3aed)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  logoTitle: { fontSize: 14, fontWeight: 700, color: '#1e293b', lineHeight: 1.2 },
  logoSub: { fontSize: 10, color: '#94a3b8', letterSpacing: .3 },
  badge: { display: 'flex', alignItems: 'center', gap: 5, padding: '3px 10px', borderRadius: 20, fontSize: 10, fontWeight: 700, letterSpacing: .8, border: '1px solid #e2e8f0', background: '#f8fafc', color: '#64748b' },
  dot: { width: 6, height: 6, borderRadius: '50%' },
  urlBar: { display: 'flex', alignItems: 'center', gap: 7, background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 6, padding: '5px 12px', minWidth: 280 },
  urlInput: { background: 'transparent', border: 'none', outline: 'none', color: '#1e293b', fontSize: 12, flex: 1, fontFamily: 'inherit' },
  btnPrimary: { display: 'flex', alignItems: 'center', gap: 6, padding: '6px 16px', borderRadius: 6, border: 'none', cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', fontWeight: 600, background: '#2563eb', color: '#fff', boxShadow: '0 1px 3px rgba(37,99,235,.25)' },

  // Tabs
  tabBar: { display: 'flex', background: '#fff', borderBottom: '1px solid #e2e8f0', padding: '0 20px' },
  tab: { display: 'flex', alignItems: 'center', gap: 6, padding: '10px 16px', background: 'transparent', border: 'none', borderBottom: '2px solid transparent', color: '#64748b', cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', fontWeight: 500 },
  tabActive: { color: '#2563eb', borderBottomColor: '#2563eb', fontWeight: 600 },

  // Body layouts
  body: { display: 'flex', flex: 1, flexDirection: 'column', overflow: 'hidden' },
  scenarioWrap: { display: 'flex', flexDirection: 'column', flex: 1, overflow: 'auto' },
  twoCol: { display: 'flex', gap: 14, padding: '0 16px 16px', alignItems: 'flex-start', flex: 1 },

  // Builder/Script toggle
  toggleBar: { display: 'flex', alignItems: 'center', gap: 16, padding: '10px 16px', background: '#fff', borderBottom: '1px solid #e2e8f0' },
  toggleGroup: { display: 'flex', background: '#f1f5f9', borderRadius: 8, padding: 3, gap: 2 },
  toggleBtn: { display: 'flex', alignItems: 'center', gap: 6, padding: '5px 14px', borderRadius: 6, border: 'none', cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', fontWeight: 500, color: '#64748b', background: 'transparent' },
  toggleActive: { background: '#fff', color: '#2563eb', fontWeight: 700, boxShadow: '0 1px 3px rgba(0,0,0,.10)' },
  toggleHint: { display: 'flex', alignItems: 'center', gap: 10, flex: 1 },
  syncBtn: { display: 'flex', alignItems: 'center', gap: 4, padding: '4px 12px', borderRadius: 5, border: '1px solid #bfdbfe', background: '#eff6ff', color: '#2563eb', cursor: 'pointer', fontSize: 11, fontFamily: 'inherit', fontWeight: 600 },
  errorBanner: { display: 'flex', alignItems: 'center', gap: 7, padding: '7px 16px', background: '#fef3c7', borderBottom: '1px solid #fde68a', color: '#92400e', fontSize: 11 },

  // Panels
  panel: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 10, overflow: 'hidden', flex: 1, boxShadow: '0 1px 4px rgba(0,0,0,.04)' },
  panelHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', borderBottom: '1px solid #f1f5f9', background: '#f8fafc', flexWrap: 'wrap', gap: 6 },
  panelTitle: { display: 'flex', alignItems: 'center', gap: 7, fontWeight: 700, color: '#1e293b', fontSize: 12, letterSpacing: .2 },
  headActions: { display: 'flex', alignItems: 'center', gap: 5, flexWrap: 'wrap' },
  countPill: { marginLeft: 6, padding: '1px 7px', borderRadius: 10, background: '#dbeafe', color: '#2563eb', fontSize: 10, fontWeight: 600 },

  // Chart
  chartBox: { padding: '12px 14px 6px', borderBottom: '1px solid #f1f5f9' },
  chartMeta: { display: 'flex', gap: 12, paddingTop: 6, fontSize: 11, color: '#94a3b8' },
  metaChip: { display: 'flex', alignItems: 'center', gap: 4 },

  // Stages
  stageRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '7px 10px', marginBottom: 6, borderRadius: 7, background: '#f8fafc', border: '1px solid #e2e8f0', borderLeft: '3px solid #e2e8f0' },
  stageTag: { width: 92, padding: '2px 7px', borderRadius: 5, fontSize: 11, fontWeight: 700, textAlign: 'center', flexShrink: 0 },
  fGroup: { display: 'flex', flexDirection: 'column', gap: 2, fontSize: 10, color: '#94a3b8', flexShrink: 0 },
  fLabel: { display: 'flex', alignItems: 'center', gap: 3, textTransform: 'uppercase', letterSpacing: .4 },
  numInput: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 5, color: '#1e293b', padding: '4px 8px', width: 76, fontFamily: 'inherit', fontSize: 12, outline: 'none' },
  rowBtns: { display: 'flex', gap: 3, marginLeft: 'auto' },
  iconBtn: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 4, color: '#94a3b8', cursor: 'pointer', padding: '3px 5px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  iconDanger: { color: '#dc2626', borderColor: '#fca5a5' },
  optRow: { display: 'flex', gap: 20, padding: '10px 14px', borderTop: '1px solid #f1f5f9', background: '#f8fafc' },

  // Endpoints
  epHead: { display: 'flex', alignItems: 'center', gap: 8, padding: '5px 14px 6px', fontSize: 10, color: '#94a3b8', letterSpacing: .5, textTransform: 'uppercase', borderBottom: '1px solid #f1f5f9' },
  epGroup: { borderBottom: '1px solid #f8fafc' },
  epRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '7px 14px', cursor: 'pointer' },
  methodBadge: { padding: '2px 6px', borderRadius: 4, border: '1px solid', fontSize: 10, fontWeight: 700, fontFamily: 'inherit', cursor: 'pointer', width: 64, textAlign: 'center', flexShrink: 0 },
  pathInput: { flex: 1, background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 5, color: '#475569', padding: '4px 8px', fontFamily: 'inherit', fontSize: 12, outline: 'none' },
  nameInput: { width: 120, background: 'transparent', border: 'none', color: '#94a3b8', padding: '4px 4px', fontFamily: 'inherit', fontSize: 11, outline: 'none', flexShrink: 0 },
  statusInput: { width: 66, background: 'transparent', border: 'none', color: '#94a3b8', padding: '4px 2px', fontFamily: 'inherit', fontSize: 11, outline: 'none', flexShrink: 0 },
  epExpanded: { display: 'flex', gap: 12, padding: '10px 14px 14px 44px', background: '#f8fafc', flexWrap: 'wrap' },
  expLabel: { display: 'flex', flexDirection: 'column', gap: 3, fontSize: 11, color: '#64748b', flex: 1, minWidth: 180 },
  codeArea: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 5, color: '#475569', padding: '6px 8px', fontFamily: "'Fira Code','JetBrains Mono',monospace", fontSize: 11, outline: 'none', resize: 'vertical' },

  // Script mode
  scriptWrap: { flex: 1, padding: '0 16px 16px', display: 'flex', flexDirection: 'column' },
  scriptPanel: { display: 'flex', gap: 14, flex: 1, minHeight: 0 },
  scriptSidebar: { width: 220, display: 'flex', flexDirection: 'column', gap: 10, flexShrink: 0 },
  sideCard: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 8, overflow: 'hidden', boxShadow: '0 1px 3px rgba(0,0,0,.04)' },
  sideCardHead: { display: 'flex', alignItems: 'center', gap: 6, padding: '7px 10px', background: '#f8fafc', borderBottom: '1px solid #f1f5f9', fontSize: 11, fontWeight: 700, color: '#475569' },
  sideRow: { display: 'flex', alignItems: 'center', gap: 7, padding: '5px 10px', borderBottom: '1px solid #f8fafc', fontSize: 11 },
  sideTag: { padding: '1px 5px', borderRadius: 3, fontSize: 9, fontWeight: 700, flexShrink: 0 },
  sideVal: { color: '#1e293b', fontSize: 11 },
  sideMeta: { color: '#94a3b8', fontSize: 10, marginLeft: 'auto', flexShrink: 0 },
  sideKey: { color: '#94a3b8', fontSize: 11, flex: 1 },
  sideEmpty: { padding: '8px 10px', color: '#cbd5e1', fontSize: 11 },
  dirtyBadge: { display: 'flex', alignItems: 'flex-start', gap: 6, padding: '8px 10px', background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 8, color: '#92400e', fontSize: 10, lineHeight: 1.5 },

  // Code editor
  editorWrap: { flex: 1, display: 'flex', flexDirection: 'column', background: '#fff', border: '1px solid #e2e8f0', borderRadius: 10, overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,.04)' },
  editorHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 14px', background: '#f8fafc', borderBottom: '1px solid #f1f5f9' },
  editorBody: { display: 'flex', flex: 1, overflow: 'auto', fontFamily: "'Fira Code','JetBrains Mono','Cascadia Code',monospace", fontSize: 12.5 },
  lineNums: { minWidth: 40, padding: '12px 0', background: '#f8fafc', borderRight: '1px solid #f1f5f9', textAlign: 'right', userSelect: 'none', flexShrink: 0 },
  lineNum: { padding: '0 10px', lineHeight: '1.65', fontSize: 11, color: '#cbd5e1' },
  codeEditor: {
    flex: 1, padding: '12px 14px', border: 'none', outline: 'none', resize: 'none',
    fontFamily: "'Fira Code','JetBrains Mono','Cascadia Code',monospace", fontSize: 12.5,
    lineHeight: 1.65, color: '#1e293b', background: '#fff', whiteSpace: 'pre', overflowWrap: 'normal',
  },

  // Buttons
  tagBtn: { display: 'flex', alignItems: 'center', gap: 3, padding: '3px 9px', borderRadius: 5, border: '1px solid', cursor: 'pointer', fontSize: 11, fontFamily: 'inherit', fontWeight: 600 },
  outBtn: { display: 'flex', alignItems: 'center', gap: 3, padding: '4px 10px', background: '#fff', border: '1px solid #e2e8f0', borderRadius: 5, color: '#475569', cursor: 'pointer', fontSize: 11, fontFamily: 'inherit' },
  outPrimary: { borderColor: '#bfdbfe', color: '#2563eb', background: '#eff6ff' },

  // Results
  metricRow: { display: 'flex', gap: 8, padding: '12px 14px', borderBottom: '1px solid #f1f5f9' },
  metricCard: { flex: 1, padding: '10px 12px', borderRadius: 8 },
  metricVal: { fontSize: 22, fontWeight: 800, letterSpacing: -1 },
  metricLbl: { fontSize: 10, color: '#94a3b8', letterSpacing: .8, marginTop: 2, textTransform: 'uppercase' },
  rtHead: { display: 'flex', alignItems: 'center', gap: 8, padding: '5px 14px 7px', fontSize: 10, color: '#94a3b8', letterSpacing: .5, textTransform: 'uppercase', borderBottom: '1px solid #f1f5f9' },
  rtRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '8px 14px', borderLeft: '3px solid transparent', borderBottom: '1px solid #f8fafc', fontSize: 12 },
  mPill: { padding: '1px 6px', borderRadius: 4, fontSize: 10, fontWeight: 700 },
  empty: { padding: '20px', textAlign: 'center', color: '#cbd5e1', fontSize: 12 },

  // Monitoring layout
  monitorWrap: { display: 'flex', flex: 1, gap: 14, padding: 16, overflow: 'hidden' },
  logPanel: { width: 320, background: '#fff', border: '1px solid #e2e8f0', borderRadius: 10, display: 'flex', flexDirection: 'column', overflow: 'hidden', flexShrink: 0, boxShadow: '0 1px 4px rgba(0,0,0,.04)' },
  logPanelHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', borderBottom: '1px solid #f1f5f9', background: '#f8fafc' },
  logBody: { flex: 1, overflow: 'auto', padding: '4px 0', fontFamily: "'Fira Code','JetBrains Mono',monospace", fontSize: 10.5 },
  logLine: { display: 'flex', gap: 6, padding: '2px 10px', lineHeight: 1.7 },
  logTime: { color: '#cbd5e1', flexShrink: 0, fontSize: 9.5 },
  logLvl: { width: 52, flexShrink: 0, fontWeight: 700, fontSize: 9.5, textTransform: 'uppercase' },
  logMsg: { flex: 1, wordBreak: 'break-all', color: '#475569' },
};